---
# Image dimensions.
image:
  width: 853
  height: 480

# The number of images to capture.
total_images: 10

# The interval between captures (in seconds).
interval: 1

# Whether to create an animated gif after capturing the time-lapse images.
create_gif: True